config/routes.rb
Yut::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/menu"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header id="centeredheader">

  <img id="logo" src="http://farm3.static.flickr.com/2803/4094262301_817a78f935.jpg">

  <center id="title">TANGUITO</center>

  <%= link_to "Home",    static_pages_home_path, class: "button" %>
  <%= link_to "Menu",    static_pages_menu_path, class: "button" %>

</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yut</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1 id="homepageheader">home</h1>
	
<p></p>

app/views/static_pages/menu.html.erb
<h1>StaticPages#menu</h1>
<p>Find me in app/views/static_pages/menu.html.erb</p>